# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-10 09:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple', '0002_profile1_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile1',
            name='loction',
            field=models.CharField(default='banglore', max_length=128),
        ),
    ]
