# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-10 10:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simple', '0004_profile1_job'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile1',
            name='job',
        ),
        migrations.RemoveField(
            model_name='profile1',
            name='loction',
        ),
    ]
